### ISSUE TITLE
Répertoire des projets de Solon

### ISSUE THREAD

**Issue by houssamkhalifeh** [VilledeMontreal/MontrealEnCommun#11]
Ajouter la documentation des projets de Solon dans le répertoire des projets partenaires du MeC [Projets Partenaires](https://github.com/VilledeMontreal/MontrealEnCommun/tree/master/ProjetsPartenaires).
Cette documentation pourrait faire des références à vos repos de code existants. 
Référer au répertoire _Gabarit_ pour ajouter votre documentation.

**Comment by vince-fabmob** [comment]
Je propose de merger ça.

**Comment by Pasc-p** [comment]
@houssamkhalifeh  L'issue peut être close si le document :https://github.com/VilledeMontreal/MontrealEnCommun/tree/master/ProjetsPartenaires/Solon répond aux attentes
